# Theme
remote_theme: epidrome/cover-card@main

# Title and tag line
title: 'Q3it'
description: 'Aseg√∫rate de que colocas tus pies en el lugar correcto y luego, mantente firme.'

# Images
avatar: 'profile.png'
background: '33.jpg'
favicon: 'd.ico'
